Remove execution context manager
dolittle/JavaScript.SDK pull request #29
Opened 2020-09-28 18:22 UTC by woksin

Also changes some of the client builder api to conform to what we have agreed on.

2020-09-29 08:25 UTC, joelhoisko requested changes

2020-09-29 08:25 UTC, joelhoisko commented on Source/events/EventStoreBuilder.ts
>  export type EventStoreBuilderCallback = (builder: EventStoreBuilder) => void;
```suggestion
```
Not used anymore, can be removed from the index file too.

2020-09-29 08:25 UTC, joelhoisko commented on Source/events/EventStoreBuilder.ts
>  export class EventStoreBuilder {
```suggestion
/**
 * Represents a builder for building an event store.
 */
export class EventStoreBuilder {
```
Just some old comments.

2020-09-30 09:16 UTC, woksin commented
I did your changes and made it build. So I guess that this is okay now

2020-09-30 09:16 UTC, merged